### ISSUE TITLE
Community Website Content

### ISSUE THREAD

**Issue by gpazuch** [ns1labs/orb#1860]
Change orb.community content.

- [x] replace github gizmo with login button
- [x] adjust header lateral spacing between nav and search gizmos
- [x] background images not adjusting properly on mobile/smaller window sizes
- [x] add github icon to bottom bar for pktvisor repo
- [x] fix hamburguer menu nav's width, last change broke it for compact view.
- [x] increase font size a little for small texts on landing page.
- [ ] make 'community' nav be a dropdown containing links to orb and pktvisor communities.
- [x] host from fork -- https://gpazuch.github.io/orb-website/
- [x] when in compact view, nav menu from hamburguer is not properly colored.
- [x] pull updated content from @rboucher-ns1 branch
- [x] fix light navbar logo - currently showing same as landing page(dark version).

-------------------------
- [x] Permalink visible on all topics
- [x] Remove duplicated github link on the bottom of the page
- [ ] Top menu should be fixed on home page
- [x] Menu Positioning does not match same of other pages
- [ ] Community Page Start Github button fix
- [x] Spacing between h1-3 headers and text content made smaller
- [ ] Check for invalid links

**Comment by manrodrigues** [comment]
My views of the new site:


First of all, I thought it was really good! I think it turned out much more professional and nice to look at. So, congratulations!

I'm going to put some points that I noticed while looking at the site.. so you can talk together and see what makes or doesn't make sense.

**Home page**

1 - On the home page, we have this icon as a clickable item, but it do not do anything. On other pages it redirects to the home page, but on the home page it looks like a misbehaving button.


![image](https://user-images.githubusercontent.com/78241475/196498308-3b1e95e8-8502-4117-91a5-2cf2a8abccff.png)


2 - I don't think "Login" is a sufficient description for the user to know they will be redirected to the orb site. If it was my first time logging in, I would think that the "Get started with orb" button would redirect me to the website, while the "Login" button would be some login to the documentation website (Could it just be my lack of adaptation?)


![image](https://user-images.githubusercontent.com/78241475/196498709-bfee51ef-4129-40e7-ab76-17f993de0524.png)

3 - the top menu of the home page could be fixed (like the other pages). As the page is long, the user could still have access to the contents of the menu. What doesn't happen for now if he scrolls down the page

**Comment by manrodrigues** [comment]
My views of the new site:


First of all, I thought it was really good! I think it turned out much more professional and nice to look at. So, congratulations!

I'm going to put some points that I noticed while looking at the site.. so you can talk together and see what makes or doesn't make sense.

**Home page**

- Permanent link icon is visible in all levels:

![icon_visible](https://user-images.githubusercontent.com/78241475/196505463-7bf29f24-0cd6-49c9-937c-a986d5349a71.gif)

- There are 2 github links (orb and pktvisor repo), but this is not explained or described and it's stranger on my first look (i also guess you should maintain the infos about our repos (version, stars, forks) somewhere on the page... 

![image](https://user-images.githubusercontent.com/78241475/196506190-857b62be-550b-4d86-a9e2-cdd83bd825e6.png)


- I don't think "Login" is a sufficient description for the user to know they will be redirected to the orb site. If it was my first time logging in, I would think that the "Get started with orb" button would redirect me to the website, while the "Login" button would be some login to the documentation website (Could it just be my lack of adaptation?)


![image](https://user-images.githubusercontent.com/78241475/196498709-bfee51ef-4129-40e7-ab76-17f993de0524.png)

- the top menu of the home page could be fixed (like the other pages). As the page is long, the user could still have access to the contents of the menu. What doesn't happen for now if he scrolls down the page

![top-menu (1)](https://user-images.githubusercontent.com/78241475/196501161-83ee831d-d4b3-4ac3-9849-65bc67645954.gif)

- There are two different "ways to color" the same button: one full of blue and other with blue and purple mixed:

![image](https://user-images.githubusercontent.com/78241475/196504454-8d3276e2-dac4-4ea8-8ce9-18f9f3647ba0.png)

personally, I think the purple was too "only on the right".. because both at the beginning and at the end, there is only this mixture on the right side. Maybe there's a technical reason why Erica decided that way, but I think we could use the button with the color mixed on top, to make the color "less divided" and also more visible at the edge of the button.


- This is very minor (and it's already on current documentation), but we have this icon as a clickable item and it do not do anything. On other pages it redirects to the home page, but on the home page it looks like a misbehaving button.


![image](https://user-images.githubusercontent.com/78241475/196498308-3b1e95e8-8502-4117-91a5-2cf2a8abccff.png)

**Comment by manrodrigues** [comment]
**Menu**

- the top menu could be fixed and have the same top and side margin structure on all pages (as mkdocs defaults to). Our custom pages have different top menu layouts.

![sup-menu](https://user-images.githubusercontent.com/78241475/196697859-d12501a9-569a-400d-9899-ca873c326452.gif)


- the left side menu changes horizontal position when some menu item is selected for all pages except "guide"

![menu_position](https://user-images.githubusercontent.com/78241475/196697150-77318601-ece0-4711-b37e-209bbdd045c3.gif)

- the contents items of the side menus of the pages have no indication of having sub contents to be expanded. These contents are only visible when the field is selected and the way to collapse the contents is to select another menu item (I think we could have expand and collapse options exposed)

![exp-items](https://user-images.githubusercontent.com/78241475/196698942-be19a9da-1a70-49dd-9381-d2bcc1e0e440.gif)

- side menus on all pages bold (as selected) the item above the chosen/exposed item

![wrong-mark](https://user-images.githubusercontent.com/78241475/196699382-77443fc5-0f7a-4303-a05b-881359ec6c33.gif)

**Comment by manrodrigues** [comment]
**naive ideas maybe for the future**

- I think the home page color transition was too abrupt in the first part. I think we could use the same transition from the bottom of the page

top:

![image](https://user-images.githubusercontent.com/78241475/196701651-b3b61137-d61c-48d7-835d-e7ea3da50c35.png)

bottom:

![image](https://user-images.githubusercontent.com/78241475/196702233-53bb89f9-1006-4ec0-a2d0-a85dd2d97b9e.png)

- the introduction part could be composed of figures, instead of text.. similar to the ns1 website

![image](https://user-images.githubusercontent.com/78241475/196702670-520b0d1c-daac-45d3-8ab4-c44064dd4473.png)

NS1 example:
![image](https://user-images.githubusercontent.com/78241475/196702925-79b6a2f6-afc6-4f26-92f2-2125c52537cc.png)

- I miss the color palette present in the content pages. The home page is super colorful and the content is practically white (not even the menu is colored). It gives a strange impression, as if we hadn't finished the pages, on my first viewing.
 
![collor](https://user-images.githubusercontent.com/78241475/196703651-f42aeceb-efaf-427a-9fb5-3172275e0bf7.gif)

- That git button with the description "star" doesn't look right

![image](https://user-images.githubusercontent.com/78241475/196703984-54268434-ec50-46d8-ae29-42878641d92a.png)

- I think the spacing between headers could be smaller and standardized

![image](https://user-images.githubusercontent.com/78241475/196705364-2d7ada66-6add-4a20-82ff-20eefa38b06f.png)

on the community page, for example, it doesn't seem to have the latest content, because it's not visible on the page.


![image](https://user-images.githubusercontent.com/78241475/196705535-f7e01a6e-9282-41c0-aeaa-6563ad91b01a.png)

**Comment by manrodrigues** [comment]
## "About" content:

- the font size of this image is very small, which makes it difficult to read. Is there any way to make it bigger?


![image](https://user-images.githubusercontent.com/78241475/197557130-96d98fd2-f442-4ac5-9aac-656d0df8d5c9.png)

- I'm not really sure about this, but I think it might make sense to bring this information from orb+pktvisor into the main concept of agent. Describing that the agent needs a backend and then highlighting the advantages of pktvisor as a backend.

![image](https://user-images.githubusercontent.com/78241475/197557776-ec2750a3-8f80-4fa3-ab7c-6de9ee6e5bbd.png)


- I think it is worth emphasizing here that the said benefit is to organize the management of the orb by groups (policies are always applied in groups), so is required and a good approach. 

![image](https://user-images.githubusercontent.com/78241475/197558479-40892cd2-7972-4c19-806f-a59d7d323ac6.png)

- I think it's worth rethinking how to distribute this information among the other core concepts, because for the user, fleet is transparent. It only has access to agents, groups, policies, sinks and datasets.

![image](https://user-images.githubusercontent.com/78241475/197559279-5b720b48-edb8-4a14-9331-8d93f635ce05.png)

**Comment by manrodrigues** [comment]
## "Getting Started" content:

- I miss those headers in the new documentation. The whole creation process is kind of mixed up (I saw that it this because of the ordered list.. but.. )

Old:

![image](https://user-images.githubusercontent.com/78241475/197563667-739d8cb7-9458-4488-8d42-5439e548123a.png)

New:

![image](https://user-images.githubusercontent.com/78241475/197563991-d95b0a3e-a6bf-48c6-932e-69ec33cddb4a.png)

**Comment by manrodrigues** [comment]
## "Guides" content:
- All those links are not available:

![image](https://user-images.githubusercontent.com/78241475/197580226-921d4057-77ce-456f-8fe4-0e4ccbf9d93f.png)

![image](https://user-images.githubusercontent.com/78241475/197580406-7038d901-9052-42c5-b5a1-7bd6d9988d85.png)

- Not sure if this code block is supposed to be clickable, but now it is a invalid link:

![image](https://user-images.githubusercontent.com/78241475/197580703-9d0deab1-0bad-481d-8e9f-79e86ce1f515.png)

- This page is empty:

![image](https://user-images.githubusercontent.com/78241475/197581059-f4caa1a4-e426-4681-acb5-319d28d83b9e.png)

- All DHCP information is with wrong information (the text here is duplicated from Edge networks)

![image](https://user-images.githubusercontent.com/78241475/197581485-e59c94c7-e7d1-49aa-b69a-6e105d8a8edb.png)


- These link is invalid:

![image](https://user-images.githubusercontent.com/78241475/197581724-95ce913c-3249-4377-a463-8ca7245e5a9f.png)

![image](https://user-images.githubusercontent.com/78241475/197581789-db3a7511-e0d8-435f-af53-022801de5415.png)

![image](https://user-images.githubusercontent.com/78241475/197581151-0c3a9c27-4507-48d5-bf7d-28c3374650d1.png)
