### ISSUE TITLE
Sink API endpoint should support partial updates

### ISSUE THREAD

**Issue by rboucher-me** [ns1labs/orb#1985]
The sink API endpoint `/api/vi/sinks/<sink-id>` should support modification of _some_ attributes without having to provide _all_ the attributes. This is needed because the password cannot be retrieved and a complete JSON body cannot be assembled for a pre-existing sink.

Updates to the following fields should be supported (without requiring all the fields to be provided in the JSON body):
- `name`
- `description`
- specific tag instances under `tags`

**Comment by mclcavalcante** [comment]
Current behavior:
- If the tags field is omitted, all tags are deleted
- If the tags field is empty, all tags are deleted
- If we already have the tags {test:true} and send an update request with JSON body with tags:{test:false}. It will be overwritten with the newest
- If we already have the tags {test:true} and send an update request with JSON body with tags:{tag:true}. It will delete the oldest tag and save the newest 

Proposed behavior:
- If the tags field is empty, all tags are deleted
- If the tags field is omitted, nothing changes
- If we already have the tags {test:true} among others and send an update request with JSON body with tags:{test:false}. It will only overwrite the one with the same key with the newest value and keep the others as it was
- If we already have the tags {test:true} among others and send an update request with JSON body with tags:{tag:true}. It will append to the preexistent ones and the result will be tags:{test:true, tag:true}

**Comment by rboucher-ns1** [comment]
@mclcavalcante I agree with your proposed behavior.

**Comment by manrodrigues** [comment]
ok.. 

My only concern is about remove tags..

Thinking about updating new tags, ok.. 
but if let's imagine it:

I already have a policy with these policies:

```
    "tags": {
        "my": "tag",
        "other": "tag",
        "test": "mine"
    }
```

Then I send a PUT request to edit the tags because I noticed that I inserted the wrong tag and I want to change my set of tags:

```
    "tags": {
        "my": "tag",
        "other": "tag"
    }
```

Instead of using only the last both tags, nothing will change.. And thinking in edit it through the ORB UI (remove the bubble) it will look like a bug for the users.
What do you think about it?

and I also have a question:

- why the name is always required on the editing process? In my thoughts, we should enable users to make put requests (to edit) with only name, only description and only tags..

**Comment by mclcavalcante** [comment]
Following up on Amanda's comment, there is a use case she came up with that is important and we've missed. Which is a partial update removing just one existent tag. To achieve this with current business logic it is needed to delete all tags and then update with the right ones, which doesn't seem good and useful.
My suggestion is to keep API that way and add one optional field "remove_tag" on the payload with all keys to be removed. Example:
    current:
    orb_tags:{
        tag:true,
        test:true
    }
    
    request: 
    remove_tags:{
        tag:true
    }

    
    wanted result:
    orb_tags:{
        test:true
    }
@rboucher-ns1 @weyrick do you guys have any thoughts on this?

**Comment by rboucher-ns1** [comment]
A few things here... 

First, the `name` field should _not_ be required _unless_ you want to modify it.

Second, we understood early on that updating/deleting tags would require some form of compromise as it isn't possible to target deletion of a specific tag using the current approach. I believe we should stick to the originally decided approach and accept this shortcoming, unless you believe there is a strong reason not to. We'll need to revisit our approach to tag management for all objects that support them in the future anyway.

**Comment by mclcavalcante** [comment]
Excellent, @rboucher-me, I agree. I'll open a quick pr to fix the name field requirement

**Comment by manrodrigues** [comment]
@rboucher-me 

I agree with continuing this approach.

Do you have any suggestions on how we can report this in the UI? Because from now on, the sink tags will be the only ones with different behavior and I think it would be good to warn the user that this is not a bug (i mean, do not remove the tag I deleted the bubble)

![tags_sink](https://user-images.githubusercontent.com/78241475/208457496-8416a9d9-90b0-4274-b8de-c1b1e8720a6e.gif)

**Comment by manrodrigues** [comment]
It's working as expected now :)

**Comment by manrodrigues** [comment]
- If the tags field is omitted, nothing changes
- If the tags field is informed and empty, all tags are deleted
- If the tags field is informed and NOT empty, new set of tags is overwritten the old one
