### ISSUE TITLE
Created tags we the same key name are being condensed into only one tag no matter how many we have.

### ISSUE THREAD

**Issue by iatdaitan** [ns1labs/orb#434]

**Comment by gpazuch** [comment]
@iatdaitan @weyrick 

So, there are two possible behaviors.

1. for same key, instead of adding new tag with same key, updates existing tag for said key

2. for same key, do not allow user to add tag, since it already exists.

I have pushed, in PRs #530 and #532 , behavior implemented as described in option 1.
Previous accepted behavior is option 2, which is pretty much a one-liner.

Is this a bug or a feature?
