### ISSUE TITLE
Agent container could have a predetermined name

### ISSUE THREAD

**Issue by manrodrigues** [ns1labs/orb#448]
Since we're not passing a name to the agent container in the provisioning command, the agent container is getting a random name (just the image calls it "orb-agent"). It would be nice to have a container's name, to make it easier to find a specific agent when we have a lot of them available.

**Comment by manrodrigues** [comment]
![Orb](https://user-images.githubusercontent.com/78241475/140555872-3700d074-948d-4c8f-a689-8e93e1628d39.jpg)

**Comment by weyrick** [comment]
https://docs.docker.com/engine/reference/commandline/run/

This should a matter of the user adding `--name` to the command. I don't think we should add it to our sample provision in command that we show in the UI, only because it makes it longer. There are many options that someone may wish to use - this is why we have to be clear in the UI and docs that this is only a sample

**Comment by gpazuch** [comment]
@iatdaitan pending close(?)
