### ISSUE TITLE
Enable upload configuration yaml file for policies

### ISSUE THREAD

**Issue by iatdaitan** [ns1labs/orb#548]
As a user, I would like to submit my policy configuration file either by typing in a text box or uploading a YAML file so that I can avoid translating it and filling a lot of fields of the policy creation form.

-- 

UI SPEC:
![image](https://user-images.githubusercontent.com/86745196/155740520-74326f09-1a5b-46ce-88a3-9f926cf1b5de.png)

FR001: It should accept both forms of YAML content (upload or type the content).
FR002: It should follow the UI SPEC above.
FR003: It should not upload the file itself but only read the content and send it as a payload to the API

NFR001: It would be good to have a highlight textbox for YAML type of content.

**Comment by gpazuch** [comment]
I'm assuming this could be either copy/paste or file upload.
Is it specific for 'upload' of a file?

**Comment by iatdaitan** [comment]
> I'm assuming this could be either copy/paste or file upload. Is it specific for 'upload' of a file?

Please consider both options.

**Comment by gpazuch** [comment]
@iatdaitan should the user make the decision at the first step?
what criteria should I use? 

empty editor -> follows through with wizard 
|| 
text on editor, follow through with yaml

Also, should the editor be required to fill in policy name and description in the input fields on first step or should he define those on the yaml too?

**Comment by gpazuch** [comment]
![image (5)](https://user-images.githubusercontent.com/1490938/157449793-22d0a586-ff2b-4cde-81c4-f07b37ee28cc.png)
![image (4)](https://user-images.githubusercontent.com/1490938/157449796-000dd87a-ccbe-44cf-aa9d-af1d53022213.png)
![image (3)](https://user-images.githubusercontent.com/1490938/157449800-c3256961-f792-4074-ac76-2dc58fa6397c.png)

**Comment by gpazuch** [comment]
![image](https://user-images.githubusercontent.com/1490938/157450252-6ae64d7c-25a1-4990-ab1d-a6ab60628ce0.png)
![image](https://user-images.githubusercontent.com/1490938/157450333-f85ea56e-a147-4614-a65a-d99f9f9e57c2.png)

**Comment by gpazuch** [comment]
![image](https://user-images.githubusercontent.com/1490938/157475948-c427d845-901b-4733-949b-37f1357fdc9a.png)
new design from @eric-daitan 

* I'll move the selector to step #2
* I'll need a text for step #2.
* Step 3 will be conditional do user choice of 'WIZARD' || 'YAML' (question @iatdaitan @weyrick - should tags be added on third step still or via YAML?)

**Comment by iatdaitan** [comment]
@gpazuch if we do have tags for policies, please keep it for both options.
For step 2 you may use "YAML FILE - Create of upload you policy yam file"

**Comment by gpazuch** [comment]
```
{
  "name": "yaml_policy_regular",
  "description": "",
  "backend": "pktvisor",
  "format": "yaml",
  "policy_data": "kind: collection\ninput:\n  tap: default_pcap\n  input_type: pcap\nhandlers:\n  modules:\n    handler_dhcp_1:\n      type: dhcp\n    handler_dns_1:\n      type: dns",
  "version": 1
}
```

I'm having a 500 return on this payload request for a new agent policy.
@mclcavalcante or @dscabral can u paste a valid yaml here on the comments so I can test this?
Thx

**Comment by gpazuch** [comment]
```{
  "name": "yaml_policy_testttttt",
  "description": "",
  "backend": "pktvisor",
  "format": "yaml",
  "policy_data": "visor:\n  handlers:\n    modules:\n      default_dns:\n        type: dns\n      default_net:\n        type: net\n  input:\n    input_type: pcap\n  tap: mydefault\n  kind: collection\nversion: \"1.0\""
}```

thx @mclcavalcante @leoparente

**Comment by manrodrigues** [comment]
- Back button for policies first page is not working anymore:

![back_button](https://user-images.githubusercontent.com/78241475/159498719-01231565-3187-48fb-b867-28dea56e1cd1.gif)

- Unable to choose the handler (next is ending creation process)

![missing_handler](https://user-images.githubusercontent.com/78241475/159499154-2cdc8da4-43c0-4030-a6cb-77202213aad0.gif)


Note that is without handler:
![image](https://user-images.githubusercontent.com/78241475/159499112-aadc8937-e778-4d98-98f4-7c1aabf9450f.png)

Option to wizard mode is disabled on editing process:

![image](https://user-images.githubusercontent.com/78241475/159499689-77335352-f530-4e91-8753-1930da816fb2.png)

- When the policy is created through yaml option, some information are missing on policies details (handler, input details)

![image](https://user-images.githubusercontent.com/78241475/159501922-d857a2e3-5c5e-4d74-8b46-c1fd7605734f.png)

- When the policy is created trough yaml option, on editing process even when the option for wizard mode is disabled we have no option to insert a yaml. Instead of this, user is being redirected to handlers page and help message about yaml keeps being displayed on the left top of the page:

![image](https://user-images.githubusercontent.com/78241475/159503055-c041eb90-9a58-4970-80e1-fa84ef9c074b.png)

**Comment by manrodrigues** [comment]
Also, I noticed that the functionality of uploading a file has not yet been implemented. Do we have a separate card for that, @gpazuch ?

**Comment by manrodrigues** [comment]
Ok

Last commit: https://github.com/ns1labs/orb/commit/3a80dfce9e824daea58ff483d1cc85867dcd4a34

#1018 
#1019 
#1020 
#1021 

The issued mentioned above will support our future tasks..
