### ISSUE TITLE
Create policy view page with initial policy details

### ISSUE THREAD

**Issue by iatdaitan** [ns1labs/orb#984]
As a user, I would like to have access to a dedicated page with detailed information about and specific policy so I can tell right away what that policy is aiming for.

-- 

**Screenshot**: 
![image](https://user-images.githubusercontent.com/86745196/160403246-546c28d9-e0c5-44f9-a5d4-8178c32abb88.png)

**FR001**: The dedicated page should follow the UI Spec design located on Figma.

**FR002**: The heading should show "Policy View".

**FR003**: It should have a section named "Agent Policy Details" which will hold the following information: Policy Name, Policy Description, and tags.

**Comment by gpazuch** [comment]
![image](https://user-images.githubusercontent.com/1490938/160876259-8d91b2d6-cba7-43e9-bd3b-31fe77d18fb7.png)

**Comment by manrodrigues** [comment]
1- Page name must be "Agent View", instead of "Agent View"
2 - The section should be named "Policy name" instead of "Name Label"
3 - Mouse icon must be different when is over the policy name
4 - Dataset active is always empty, even when we do have datasets actives

![image](https://user-images.githubusercontent.com/78241475/160929276-65721b1a-2bca-4377-b4d4-c4f4dcd6d4bf.png)

![click_button](https://user-images.githubusercontent.com/78241475/160930229-1012da07-9032-4464-bff1-f906d45a20f9.gif)


![dataset_zero](https://user-images.githubusercontent.com/78241475/160930419-656eeff1-b94d-4d1b-99fa-b804468fc0b0.gif)

**Comment by gpazuch** [comment]
@manrodrigues 
I don't see whats behind #1
Where did you get reference for #2?

Will look #3 & #4

**Comment by manrodrigues** [comment]
@gpazuch i'm sorry.. It was my mistake on #1. What I mean is the name must be "Policy View" instead of "Agent view"

On #2 this is on Igor description of the activity  ``` FR003: It should have a section named "Agent Policy Details" which will hold the following information: Policy Name, ```

**Comment by manrodrigues** [comment]
@gpazuch these thinks is not solved yet:

**1- Page name must be "Policy View", instead of "Agent View"
2 - Mouse icon must be different when is over the policy name**

3 - Dataset active is always empty, even when we do have datasets actives (I saw you wrote that this is expected)

![image](https://user-images.githubusercontent.com/78241475/162355097-f04837e8-dc4c-4d18-9ceb-3ccb61e9aa18.png)


I also notice two things:

1) Handlers are always as "DNS | 1.0", independently of the real handlers used
2) Filters are always "No filter expression" even when filters are applied
